### ISSUE TITLE
tgBBBot Todo List.

### ISSUE THREAD

**Issue by ragulbalaji** [ragulbalaji/burningbridgesbot#1]
## Got some bugs to whack and features to iron out:
- [ ]  add temporary /skipturnbb for debugging
- [ ]  clean up the mess we created i.e. use more objects and functions for smooth and organised code
- [ ]  Code Comments?
- [x]  ABC joined.      _**1 of min 5 players**_
- [x]  Fix spelling mistakes      ABC 's question **_is was_**
- [ ]  TIMEOUTS for skipping missed turns and slow people
- [ ]  Clean up messy console.log()
- [ ]  Fix QnSave() issues
- [x]  More Stats Variables tracking
- [ ]  More Group Feedback while people waiting
- [ ]  Go Public, get rich
- [ ]  /joinbb should not be so laggy
- [x]  Millionaire yet?

**Comment by eleanorloh** [comment]
- [x] stats (questions revealed, hidden, times pointed at, most pointed)
- [ ] configure number of rounds per game
- [ ] reply to bot without quoting message
- [ ] aesthetic stuff, gifs, ascii in reply to /start and end game, etc (see: ww)
- [x] /players

**Comment by rhgndf** [comment]
- [ ] Use promises instead
- [ ] Save stats and game info to db
- [ ] Configuration by group admin
- [ ] /nextgame or /nextgameautojoin
